### ISSUE TITLE
Update status with webhook from other repo actions

### ISSUE THREAD

**Issue by gadenbuie** [gadenbuie/status#2]
Using https://github.com/peter-evans/repository-dispatch. The workflow in this repo is all set up but I'd need to wire it up in the workflows of the tracked repos (and document how to do it).

**Comment by gadenbuie** [comment]
- Create [a new PAT with repo and workflow access](https://github.com/settings/tokens)
- `tic::gha_add_secret("<paste_token_here>", name = "TIC_UPDATE", repo_slug = "owner/repo")` for each repo that needs the secret
- In each repo run `tic::use_update_yml()` (optional)
- In each repo update the `.github/workflows/main.yml` (or whatever name the action is) and add this step:

    ```yaml
    - name: Update status dashboard at gadenbuie/status
        uses: peter-evans/repository-dispatch@v1
        if: github.ref == 'refs/heads/HEAD' &&  matrix.config.os == 'macOS-latest' && matrix.config.r == 'release'
        with:
          token: ${{ secrets.TIC_UPDATE }}
          event-type: status-update
          repository: gadenbuie/status # where to send the event
    ```

**Comment by gadenbuie** [comment]
Adds a composite action, designed to work with [r-lib/actions/check-standard](https://github.com/r-lib/actions/blob/v2-branch/examples/check-standard.yaml)

```yaml
- name: Update status dashboard
  uses: gadenbuie/status/actions/status-update-rcmdcheck@main
  with:
    github-token-repo-scope: ${{ secrets.GITHUB_STATUS_UPDATE_TOKEN }}
    status-repo: gadenbuie/status
```

Note that the action internally includes the condition:

```
      if: |
        (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') &&
        matrix.config.os == 'ubuntu-latest' &&
        matrix.config.r == 'release'
```
